### PR TITLE
[boost] Update boost to 1.81.0

### PR DESCRIPTION
**Pull request by nataliejameson**
## Summary:

When updating to XCode 15 clang is updated. With that, some C++17/C++20 underspecified features (like unary function static type assertions) have become hard errors. These are corrected in newer versions of boost, so update the version of boost for all platforms. This change will have an associated change in the discord repository to ensure it works on both iOS and Android. 

## Test Plan:

While this built locally after regenerating pods, the test plan will be to put up the discord/ changes (I'll link below) and ensure that android and ios CI pass.

### CODE REVIEW

**Comment by Flewp** [comment]
Looks good! You'll want to merge this into `0.70.6-discord-1`, not `main`.

**Review by Flewp — APPROVED** [review]

**Comment by pmick** [comment]
Woooo! LGTM beyond what Alex said. Thank you for doing this

**Review by pmick — APPROVED** [review]

**Comment by nataliejameson** [comment]
@Flewp I rebased, and Danger is failing. I'm assuming it's just not going to work, yeah?

**Comment by Flewp** [comment]
Correct yeah! It just always fails

**Pull request merged**
